name: Release

on:
  push:
    branches:
      - master
      - beta

permissions:
  contents: write
  id-token: write
  packages: write

env:
  OUTPUT_DIR: bin
  RELEASE_DIR: release
  PLUGIN_NAME: openbao-plugin-secrets-nats
  IMAGE_NAME: ghcr.io/bonesofgiants/openbao-plugin-secrets-nats

jobs:
  version:
    name: Determine version
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '(no ci)') && !contains(github.event.head_commit.message, 'chore:')"
    outputs:
      tag: ${{ steps.version.outputs.new_tag }}
      version: ${{ steps.version.outputs.new_version }}
      changelog: ${{ steps.version.outputs.changelog }}
      type: ${{ steps.version.outputs.release_type }}
    steps:
      - uses: actions/checkout@v6
      - name: Determine next version
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          dry_run: true
          github_token: ${{ github.token }}

  build:
    name: Build
    needs: version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux', 'windows', 'darwin']
        architecture: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build the artifacts
        run: |
          make "OUTPUT_DIR=${{ env.OUTPUT_DIR }}" "GOOS=${{ matrix.os }}" "GOARCH=${{ matrix.architecture }}" VERSION=${{ needs.version.outputs.tag }} build

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-${{ matrix.os }}-${{ matrix.architecture }}
          path: ${{ env.OUTPUT_DIR }}/*
          retention-days: 1
          overwrite: true

  release:
    name: Release
    needs: [version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.OUTPUT_DIR }}
          pattern: plugin-*
          merge-multiple: true

      - name: Package & Update README.md
        id: package
        run: |
          make "OUTPUT_DIR=${{ env.OUTPUT_DIR }}" "RELEASE_DIR=${{ env.RELEASE_DIR }}" package
          make "IMAGE_NAME=${{ env.IMAGE_NAME }}" "VERSION=${{ needs.version.outputs.tag }}" "SHA256SUM=$(cat "$RELEASE_DIR/$PLUGIN_NAME-linux-amd64.sha256" | cut -d' ' -f1)" update-readme
          echo "changelog<<__EOF__" >> "$GITHUB_OUTPUT"
          echo "${{ needs.version.outputs.changelog }}" >> "$GITHUB_OUTPUT"
          echo "### sha256" >> "$GITHUB_OUTPUT"
          echo "\`\`\`" >> "$GITHUB_OUTPUT"
          echo "$(make "RELEASE_DIR=${{ env.RELEASE_DIR }}" print-sha256)" >> "$GITHUB_OUTPUT"
          echo "\`\`\`" >> "$GITHUB_OUTPUT"
          echo "__EOF__" >> "$GITHUB_OUTPUT"

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: README.md
          author_name: BonesOfGiantsCurator
          author_email: 121028010+BonesOfGiantsCurator@users.noreply.github.com
          message: |
            chore: Release ${{ needs.version.outputs.tag }}

            - Workflow: ${{ github.workflow }} (#${{ github.run_number }})
            - Actor: ${{ github.actor }}
            - Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          tag: ${{ needs.version.outputs.tag }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.version.outputs.tag }}
          name: Release ${{ needs.version.outputs.tag }}
          body: ${{ steps.package.outputs.changelog }}

      - name: Upload artifacts
        run: gh release upload "${{ needs.version.outputs.tag }}" "${{ env.RELEASE_DIR }}/*"
        env:
          GH_TOKEN: ${{ github.token }}

  push-oci:
    name: Push OCI
    needs: [version, build]
    runs-on: ubuntu-latest
    env:
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.OUTPUT_DIR }}
          pattern: plugin-*
          merge-multiple: true

      - name: Export targets
        id: export-targets
        run: echo "targets=$(make "OUTPUT_DIR=${{ env.OUTPUT_DIR }}" print-targets)" >> "$GITHUB_OUTPUT"

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Containerfile
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ needs.version.outputs.tag }}
          platforms: ${{ steps.export-targets.outputs.targets }}
          annotations: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          build-args: |
            BIN=${{ env.OUTPUT_DIR }}
            PLUGIN_NAME=${{ env.PLUGIN_NAME }}